services:
  modx-php:
    build:
      context: ./php
      args:
        MODX_VERSION: "3.2.0"
    container_name: modx-php
    restart: unless-stopped
    environment:
      TZ: Europe/Moscow
      MODX_VERSION: "3.2.0"
    volumes:
      - ./app/public:/app/public
    depends_on:
      - modx-db
    networks:
      - web
      - internal

  modx-db:
    image: mariadb:10.11
    container_name: modx-db
    restart: unless-stopped
    environment:
      TZ: Europe/Moscow
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb-file-per-table=1
    volumes:
      - modx_db_data:/var/lib/mysql
    networks:
      - internal

volumes:
  modx_db_data:

networks:
  web:
    external: true
  internal:
    driver: bridge